- id: "backend:public"
  upstream:
    preserve_host: true
    url: "http://localhost:8082"
    # strip_path: "/api/auth"
  match:
    url: "http://localhost:8080/api/auth/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "backend:private"
  upstream:
    preserve_host: true
    url: "http://localhost:8082"
    # strip_path: "/api/auth"
  match:
    url: "http://localhost:8080/api/<{profile,notifications}>/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
  mutators:
    # - handler: noop
    - handler: header
  authorizer:
    handler: allow

# https://www.ory.sh/docs/oathkeeper/guides/proxy-websockets
- id: "api:chat"
  upstream:
    preserve_host: true
    url: "http://localhost:5280"
  match:
    url: "http://localhost:8080/ws"
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: json
